# -*- coding: utf-8 -*-
"""Tic Tac Toe Game OFFICIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zw4vO3zE60V2JALaG6BdaEqYbkk-0WON
"""

import random

# Using a game list to visualize the tic-tac-toe board
tic_tac_toe = [
    ["1", "2", "3"],
    ["4", "5", "6"],
    ["7", "8", "9"]
]

#As long as game runs, it will loop, to allow players to play again
game_running = True
#Aet number of moves to 0, to be able to set a limit
total_move = 0

#How to win
# All potential combinations that will result in a win = end the game

def horizontal_win(a, b, c):
    #Checks for horizontal win
    global tic_tac_toe
    global game_running
    if b == tic_tac_toe[a][0] == tic_tac_toe[a][1] == tic_tac_toe[a][2]:
        print("Congratulations! " + c + " wins! Thank you for playing!")
        game_running = False

def vertical_win(a, b, c):
    #Checks for vertical win
    global tic_tac_toe
    global game_running
    if b == tic_tac_toe[0][a] == tic_tac_toe[1][a] == tic_tac_toe[2][a]:
        print("Congratulations! " + c + " wins! Thank you for playing!")
        game_running = False

def diagonal_win_right(b, c):
    #Checks for diagonal win from right
    global tic_tac_toe
    global game_running
    if b == tic_tac_toe[0][0] == tic_tac_toe[1][1] == tic_tac_toe[2][2]:
        print("Wow! " + c + " wins! Thank you for playing!")
        game_running = False

def diagonal_win_left(b, c):
    #Checks for diagonal win from left
    global tic_tac_toe
    global game_running
    if b == tic_tac_toe[0][2] == tic_tac_toe[1][1] == tic_tac_toe[2][0]:
        print("Amazing! " + c + " wins! Thank you for playing!")
        game_running = False


def board():
    '''This prints out the board'''
    for x in range (3):
        print(tic_tac_toe[x])
board()
print("This grid represents a Tic-Tac-Toe board.")

def restart():
  '''This restarts the board'''
  global tic_tac_toe
  global total_move
  tic_tac_toe = [
      ["1", "2", "3"],
      ["4", "5", "6"],
      ["7", "8", "9"]
    ]
  total_move = 0
  print("The board has been restarted.")

def replay():
  '''Asks players whether they wish to continue playing or to quit after game is completed'''
  global game_running
  global total_move
  while game_running == False:
    play_again = input("Would you like to play again? please answer y/n: ").lower()
    if play_again == "y":
      game_running = True
      restart()
      game_play()
    elif play_again == "n":
      print("Thanks for playing! Come play again soon! :)")
      break
    else:
      print("Please only enter y or n")
#The loop will continue as long as the game is running

def game_play():
  '''Runs the game'''
  global game_running
  global total_move
  while game_running == True and total_move == 0:
  #game start message using class
    class GreetingPrinter:
      def print_greeting(self):
        print(f"Hello, welcome to a game of tic-tac-toe! You will be playing against the opponent next to you. Good luck, and have fun!")
    greeting1 = GreetingPrinter()
    greeting1.print_greeting()
#receives inputs to take as players' names
    player1 = input("Player 1, what's your name? ")
    player2 = input("Player 2, what's your name? ")

#determines which player goes first
    play_roll = random.randint(1,2)
    print("The computer rolled a: ", play_roll)

    if play_roll == 1:
      print( player1, "goes first.")
    elif play_roll == 2:
      print(player2, "goes first.")


#O and X choice
#The code randomly chooses from the X and O list and assigns the X and O to the players.
#To ensure that the choice is not repeated, it is removed from the list
    options = ["X", "O"]
    player1_choice = random.choice(options)
    options.remove(player1_choice)
    player2_choice = random.choice(options)
    print(player1, "you are", player1_choice)
    print(player2, "you are", player2_choice)



#Try and except accounts for a string user input
    while game_running == True and total_move <= 9:
      if play_roll == 1:
        try:
          placement_1 = int(input(player1 +"," +" " + "on which number would you like to place your " + player1_choice+ "? "))

          if (placement_1>=1 and placement_1<=9):
            while tic_tac_toe[(placement_1-1)//3][(placement_1-1)%3] == player1_choice or tic_tac_toe[(placement_1-1)//3][(placement_1-1)%3] == player2_choice:
              placement_1 = int(input(player1 +","+ " " + "this space is already taken. Please try another number. "))

            tic_tac_toe[(placement_1-1)//3][(placement_1-1)%3] = player1_choice
            board()
            horizontal_win(((placement_1 - 1)//3), player1_choice, player1)
            vertical_win(((placement_1 - 1)%3), player1_choice, player1)
            diagonal_win_right(player1_choice, player1)
            diagonal_win_left(player1_choice, player1)
            total_move += 1
            play_roll = 2
        except ValueError:
          placement_1 = int(input("Invalid input. Please enter a number. "))

      elif play_roll == 2:
        try:
          placement_2 = int(input(player2 +"," +" " + "on which number would you like to place your " + player2_choice+ "? "))

          if (placement_2>=1 and placement_2<=9):
            while tic_tac_toe[(placement_2-1)//3][(placement_2-1)%3] == player1_choice or tic_tac_toe[(placement_2-1)//3][(placement_2-1)%3] == player2_choice:
              placement_2 = int(input(player2 +","+ " " + "this space is already taken. Please try another number. "))

            tic_tac_toe[(placement_2 - 1)//3][(placement_2 - 1)%3] = player2_choice
            board()
            horizontal_win(((placement_2 - 1)//3), player2_choice,  player2)
            vertical_win(((placement_2 - 1)%3), player2_choice,  player2)
            diagonal_win_right(player2_choice, player2)
            diagonal_win_left(player2_choice,  player2)
            total_move += 1
            play_roll = 1
        except ValueError:
          placement_2 = int(input("Invalid input. Please enter a number. "))

      if total_move == 9 and game_running == True:
        print("It's a tie. The board is filled up, no more spaces left.")
        game_running = False
        break


game_play()
replay()

#Reference: https://www.w3schools.com/python/python_try_except.asp

